### ISSUE TITLE
Match last tier with dot operator

### ISSUE THREAD

**Issue by s-andringa** [q-m/tiered_category_expressions#2]
Sometimes subcategories contradict a parent that I'd like to match against, in such cases I need to be able to match the parent, all of its descendants, _except_ the contracting child. E.g. I need to be able to write a TCE that:
```
Matches
["Petfood", "Dogfood"]
["Petfood", "Dogfood", "Dry"]
["Petfood", "Dogfood", "Moist"]

But does not match
["Petfood", "Dogfood", "Poop bags"]
```
### Proposal

A 'last tier' operator (`.`), which should enable users to:

1. End the TCE with a dot when it should not match a full subtree
2. Insert a dot where it can match a category's last tier

### Examples
```
foo.

Matches exclusively
["foo"]
```
```
foo. > bar

Matches as regular (w/o dot), but including
["foo"]
```
```
foo. > bar.

Matches exclusively
["foo"]
["foo", "bar"]
```
```
foo > !bar.

Matches
["foo", "baz"]
["foo", "qux"]
["foo", "quux"]
etc

Does not match
["foo", "bar"]
["foo", "baz", "qux"]
["foo", "baz", "qux", "quux"]
etc
```

```
foo. > !bar

Matches
["foo"]
["foo", "baz"]
["foo", "baz", "qux"]
etc

Does not match
["foo", "bar"]
["foo", "bar", "baz"]
["foo", "bar", "baz", "qux"]
etc
```
```
petfood > dogfood. > !poop bags

Matches
["Petfood", "Dogfood"]
["Petfood", "Dogfood", "Dry"]
["Petfood", "Dogfood", "Moist"]
etc

Does not match
["Petfood", "Dogfood", "Poop bags"]
["Petfood", "Dogfood", "Poop bags", "Extra large"]
etc
```

**Comment by s-andringa** [comment]
@wvengen What do you think?

**Comment by wvengen** [comment]
Interesting, nice addition!
I wonder if `foo. > bar` would better be written as `foo. | (foo > bar)` or `foo (. | > bar)` or `foo > (. | bar)`.

**Comment by s-andringa** [comment]
Thanks for your ideas @wvengen. I carefully considered them, but I'm not sure for a number of reasons:

- While `foo. | (foo > bar)` is my favorite suggestion, as I really like the idea of nested/grouped TCEs,  it can easily lead to a lot of repetition and hard to read expressions, especially in more complex cases. E.g. `foo. > bar. > baz. > !qux` vs. `foo. | (foo > (bar. | (bar > baz. | (baz > !qux))`. However, nested TCEs could very well be a separate, future improvement on its own.
- I think `foo > (. | bar)` (or `foo > .` for that matter) doesn't fit the philosophy that a TCE should look like the category it is intented to match as much as possible. The `>` signals that the TCE matches categories of at least two tiers, while it would also match a single `["foo"]`. I can see where you come from, but I don't think non-technical users (our target audience) would think of 'the end' as a tier. (Confirmed by 1 non-technical person.)
- `foo (. | > bar)` seems a bit contrived, and doesn't align with the idea of grouping (sub)TCEs, as`(. | > bar)` isn't a valid TCE on its own.

@deborahwinkel: Care to throw in your 2 cts?

**Comment by deborahwinkel** [comment]
```
foo > !bar.

Matches
["foo", "baz"]
["foo", "qux"]
["foo", "quux"]
etc

Does not match
["foo", "bar"]
["foo", "baz", "qux"]
["foo", "baz", "qux", "quux"]
etc
```

Are the last 2 lines correct? Shouldn't it say 'bar' instead of 'baz'? Because I don't see why those 2 lines are in the does-not-match list. 

For the rest it seems logical to me :)

**Comment by s-andringa** [comment]
In this example the dot is supposed to mean "this must be the last tier (ie subcategory, level)". Even though the first two tiers of the last two examples match the expression, they both have additional tiers ("qux", "quux"). Therefore "baz" isn't the last tier and the expression doesn't match. A simpler example:

```rb
"foo."

# Only matches
["foo"] # foo is last tier

# Does not match
["foo", "bar"] # the category is not supposed to have a second tier
["bar"] # does not match "foo"
```

This is true if the expression _ends_ with a dot.

When a dot is succeeded by one or more tiers, as in "foo. > bar", it means "this _can_ be the last tier, but if it isn't then the rest should match the succeeding rules". So there's a slight difference there. For instance:
```rb
"foo > !bar. > qux"

# Matches
["foo", "baz"] # second tier is last tier
["foo", "baz", "qux"] # there's a third tier and it matches "qux"
["foo", "baz", "qux", "quux"] # and there's no dot at the end, so all descendants match
["foo", "qux"] # again, second tier is last tier
["foo", "qux", "baz"] # etc

# Does not match
["foo", "bar"]
["foo", "bar", "qux"]
["foo", "bar", "qux", "quux"]
["foo", "baz", "quux"]
etc
```

Does it make sense now? Or maybe you find any of @wvengen's proposals clearer?

**Comment by deborahwinkel** [comment]
clear!
